#!/usr/bin/python3
import sys
import yaml
from pygments import highlight
from pygments.lexers import CLexer
from pygments.lexers import CppLexer
from pygments.lexers import Python3Lexer
from pygments.lexers import SchemeLexer
from pygments.lexers import LuaLexer
from pygments.lexers import BashLexer
from pygments.lexers import MakefileLexer
from pygments.lexers import TexLexer
from pygments.lexers import GnuplotLexer
from pygments.lexers import TextLexer
from pygments.lexers import EmacsLispLexer
from pygments.formatters import HtmlFormatter

def make_alnum_text(text):
    alnum_text = ''
    for c in text:
        if c.isalnum():
            alnum_text += c
    return alnum_text

def orez_output(text):
    sys.stdout.write(text)

def orez_code_highlight(code, lexer):
    if code.isspace():
        return code
    n_chars = len(code)
    # 保留首部空白字符
    leading_spaces = ''
    for i in range(0, n_chars):
        if not code[i].isspace():
            leading_spaces = code[:i]
            break
    # 保留尾部空白字符
    trailing_spaces = ''
    for i in range(-1, -(n_chars + 1), -1):
        if not code[i].isspace():
            if i < -1:
                trailing_spaces = code[i+1:]
            break
    # 代码高亮
    code = code.strip()
    hl_code = highlight(code, lexer(), HtmlFormatter(nowrap=True))
    # 将 highlight 引入的首尾空白字符清除
    hl_code = hl_code.strip()
    # 将首部空白字符与尾部空白字符放回去
    hl_code = leading_spaces + hl_code + trailing_spaces
    return hl_code

def lang_mark_warn(code_frag, info):
    sys.stderr.write("@ {0} # : ".format(code_frag['NAME'].strip("'")))
    sys.stderr.write(info)

def format_code_frag_ref(ref):
    name = ref['NAME'].strip("'")
    name_alnum = make_alnum_text(name)
    if 'ID_ARRAY' in ref:
        orez_output('<span class="orez-callee-text"># %s @</span>' % name)
        for id in ref['ID_ARRAY']: # 尾随一组 \at 生成的页码
            orez_output(' <a href="#%s%d">[%d]</a>' % (name_alnum, id, id))
    else:  # 源码域名后面是一个 \at 生成的页码
        orez_output('<a href="#%s" class="orez-callee-link"># %s @</a>' 
                    % (name_alnum, name))
    orez_output('\n')

if __name__=="__main__":
    # 解析 yaml
    x = None
    if len(sys.argv) > 1:
        f = open(sys.argv[1])
        x = yaml.load(f)
        f.close()
    else:
        x = yaml.load(sys.stdin)
    # 为代码高亮准备词法解析器的查找表
    lexers = {'c':CLexer, 'c++':CppLexer, 'python':Python3Lexer, 
              'scheme':SchemeLexer, 'lua':LuaLexer, 'tex':TexLexer, 
              'makefile':MakefileLexer, 'gnuplot':GnuplotLexer,
              'plain':TextLexer, 'elisp':EmacsLispLexer, 'bash':BashLexer}

    for e in x:
        if 'DOC_FRAG' in e:
            orez_output(e['DOC_FRAG'].strip("'"))
            orez_output("\n\n")
        else:
            cf = e['CODE_FRAG']
            name = cf['NAME'].strip("'")
            name_alnum = make_alnum_text(name)
            
            # pre begin
            if 'ID' in cf:
                orez_output('<pre id="%s%d" class="orez-code-fragment">\n'
                            % (name_alnum, cf['ID']))
            else:
                orez_output('<pre id="%s" class="orez-code-fragment">\n' % (name_alnum))
            
            # format code fragment name
            orez_output('<span class="orez-code-fragment-name">@ ')
            orez_output(name)
            orez_output(' #</span>')
            
            # format target label and operator
            if 'OPERATOR' in cf:
                if 'TARGET_LABEL' in cf:
                    target_label = cf['TARGET_LABEL'].strip("'")
                    long_target_label = name_alnum + '-' + make_alnum_text(target_label)
                    orez_output('  <a class="orez-target-label" ')
                    orez_output('href="#{0}">&lt;{1}&gt;</a>'.format(long_target_label, target_label))
                orez_output('  <span class="orez-symbol">{0}</span>'.format(cf['OPERATOR']))
            
            # format source label
            if 'SOURCE_LABEL' in cf:
                source_label = cf['SOURCE_LABEL'].strip("'")
                long_source_label = name_alnum + '-' + make_alnum_text(source_label)
                orez_output('\n<span id="%s" class="zero-source-label">&lt;%s&gt;</span>'
                            % (long_source_label, source_label))
            orez_output("\n")
            
            # format code fragment body
            for o_e in cf['CONTENT']:
                if 'SNIPPET' in o_e:
                    snippet = o_e['SNIPPET'].strip("'")
                    if 'LANG' in cf:
                        lang = cf['LANG'].lower()
                        if lang not in lexers:
                            lang_mark_warn(cf, "There is not lexer for me!")
                            orez_output(snippet)
                        else:
                            lexer = lexers[lang]
                            hl_code = orez_code_highlight(snippet, lexer)
                            orez_output(hl_code)
                    else:
                        lang_mark_warn(cf, "No language mark for me!")
                        orez_output(snippet)
                elif 'INDENT' in o_e:
                    orez_output(o_e['INDENT'])
                elif 'REF' in o_e:
                    format_code_frag_ref(o_e['REF'])
                else:
                    illegal_code_frag_warning(cf)
            orez_output('\n')
            
            # format emissions 
            if 'EMISSIONS' in cf:
                for o_e in cf['EMISSIONS']:
                    emi = o_e['EMISSION']
                    # 由于要为 emi_name 增加了 '=> ' 前缀，若 emisi_name 为多行文本，为了美观，
                    # 那么每个换行符后需要增加三个空白字符作为 padding
                    emi_name = emi['NAME'].strip("'").replace('\n', '\n   ')
                    emi_name_alnum = make_alnum_text(emi_name)
                    if 'ID' in emi:
                        emi_link = '<span class="orez-symbol">=&gt;</span> ' + \
                                   '<a href="#{0}{1}" class="proc-emissions-name">{2}</a>\n'
                        orez_output(emi_link.format(emi_name_alnum, emi['ID'], emi_name))
                    else:
                        emi_link = '<span class="orez-symbol">=&gt;</span> ' + \
                                   '<a href="#{0}" class="proc-emissions-name">{1}</a>\n'
                        orez_output(emi_link.format(emi_name_alnum, emi_name))
            orez_output("</pre>\n\n")
